// firefox config for neko
lockPref("browser.tabs.closeWindowWithLastTab", false);
lockPref("app.update.auto", false);
lockPref("app.update.enabled", false);
lockPref("app.update.silent", true);
lockPref("browser.cache.disk.capacity", 1000);
lockPref("browser.download.useDownloadDir", false);
lockPref("browser.rights.3.shown", true);
lockPref("browser.search.update", false);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("extensions.update.enabled", false);
lockPref("plugin.default_plugin_disabled", false);
lockPref("plugin.scan.plid.all", true);
lockPref("plugins.hide_infobar_for_missing_plugin", true);
lockPref("profile.allow_automigration", false);
lockPref("signon.prefillForms", false);
lockPref("signon.rememberSignons", false);
lockPref("xpinstall.enabled", false);
lockPref("xpinstall.whitelist.required", true);
lockPref("browser.download.manager.retention", 0);
lockPref("browser.download.folderList",	2);
lockPref("browser.download.forbid_open_with", true);
lockPref("browser.safebrowsing.downloads.enabled", false);
lockPref("browser.safebrowsing.downloads.remote.enabled",	false);
lockPref("browser.helperApps.alwaysAsk.force",	false);
lockPref("browser.helperApps.neverAsk.saveToDisk",	"application/zip,application/octet-stream,image/jpeg,application/vnd.ms-outlook,text/html,application/pdf");
lockPref("browser.helperApps.neverAsk.openFile",	"application/zip,application/octet-stream,image/jpeg,application/vnd.ms-outlook,text/html,application/pdf");
//lockPref("browser.newtabpage.activity-stream.default.sites",	"");
// dark mode
lockPref("reader.color_scheme", "dark");
lockPref("devtools.theme", "dark");
lockPref("ui.systemUsesDarkTheme", 1);
lockPref("lightweightThemes.usedThemes","[]");
lockPref("lightweightThemes.selectedThemeID", "firefox-compact-dark@mozilla.org");
lockPref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
lockPref("browser.theme.toolbar-theme", 0);
lockPref("browser.in-content.dark-mode", true);

// mousewheel fix
lockPref("mousewheel.default.delta_multiplier_x", 45);
lockPref("mousewheel.default.delta_multiplier_y", 45);
lockPref("mousewheel.default.delta_multiplier_z", 45);

// disable vie wbtn
lockPref("browser.tabs.firefox-view", false);
lockPref("browser.tabs.firefox-view-next", false);
lockPref("browser.tabs.tabmanager.enabled", false);

// telemetry
lockPref("devtools.onboarding.telemetry.logged", false);
lockPref("toolkit.telemetry.updatePing.enabled", false);
lockPref("browser.newtabpage.activity-stream.feeds.telemetry", false);
lockPref("browser.newtabpage.activity-stream.telemetry", false);
lockPref("browser.newtabpage.activity-stream.feeds.discoverystreamfeed", false);
lockPref("browser.newtabpage.activity-stream.showSponsored", false);
lockPref("browser.ping-centre.telemetry", false);
lockPref("toolkit.telemetry.bhrPing.enabled", false);
lockPref("toolkit.telemetry.enabled", false);
lockPref("toolkit.telemetry.firstShutdownPing.enabled", false);
lockPref("toolkit.telemetry.hybridContent.enabled", false);
lockPref("toolkit.telemetry.newProfilePing.enabled", false);
lockPref("toolkit.telemetry.reportingpolicy.firstRun", false);
lockPref("toolkit.telemetry.shutdownPingSender.enabled", false);
lockPref("toolkit.telemetry.unified", false);
lockPref("toolkit.telemetry.archive.enabled", false);
lockPref("datareporting.healthreport.uploadEnabled", false);
lockPref("datareporting.policy.dataSubmissionEnabled", false);
lockPref("datareporting.sessions.current.clean", false);

// disable activity stream
lockPref("browser.newtabpage.enabled", false); 
lockPref("browser.newtab.preload", false); 
lockPref("browser.newtabpage.activity-stream.aboutHome.enabled", false);

// disable geo
lockPref("geo.provider.ms-windows-location", false);
lockPref("geo.provider.use_gpsd", false);
lockPref("geo.provider.use_corelocation", false);
lockPref("geo.provider.use_geoclue", false);
lockPref("browser.region.network.url", "");
lockPref("browser.region.update.enabled", false);

/// SET PRTEF?
defaultPref("app.normandy.api_url", "");

// user_pref("app.normandy.api_url", "");
// user_pref("app.normandy.enabled", false);
// user_pref("app.shield.optoutstudies.enabled", false);
// user_pref("app.update.auto", false);
// user_pref("beacon.enabled", false);
// user_pref("breakpad.reportURL", "");
// user_pref("browser.aboutConfig.showWarning", false);
// user_pref("browser.cache.offline.enable", false);
// user_pref("browser.crashReports.unsubmittedCheck.autoSubmit", false);
// user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
// user_pref("browser.crashReports.unsubmittedCheck.enabled", false);
// user_pref("browser.disableResetPrompt", true);
// user_pref("browser.newtab.preload", false);
// user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
// user_pref("browser.newtabpage.enabled", false);
// user_pref("browser.newtabpage.enhanced", false);
// user_pref("browser.newtabpage.introShown", true);
// user_pref("browser.safebrowsing.appRepURL", "");
// user_pref("browser.safebrowsing.blockedURIs.enabled", false);
// user_pref("browser.safebrowsing.downloads.enabled", false);
// user_pref("browser.safebrowsing.downloads.remote.enabled", false);
// user_pref("browser.safebrowsing.downloads.remote.url", "");
// user_pref("browser.safebrowsing.enabled", false);
// user_pref("browser.safebrowsing.malware.enabled", false);
// user_pref("browser.safebrowsing.phishing.enabled", false);
// user_pref("browser.selfsupport.url", "");
// user_pref("browser.send_pings", false);
// user_pref("browser.sessionstore.privacy_level", 0);
// user_pref("browser.shell.checkDefaultBrowser", false);
// user_pref("browser.startup.homepage_override.mstone", "ignore");
// user_pref("browser.tabs.crashReporting.sendReport", false);
// user_pref("browser.urlbar.groupLabels.enabled", false);
// user_pref("browser.urlbar.quicksuggest.enabled", false);
// user_pref("browser.urlbar.speculativeConnect.enabled", false);
// user_pref("browser.urlbar.trimURLs", false);
// user_pref("datareporting.healthreport.service.enabled", false);
// user_pref("datareporting.healthreport.uploadEnabled", false);
// user_pref("datareporting.policy.dataSubmissionEnabled", false);
// user_pref("device.sensors.ambientLight.enabled", false);
// user_pref("device.sensors.enabled", false);
// user_pref("device.sensors.motion.enabled", false);
// user_pref("device.sensors.orientation.enabled", false);
// user_pref("device.sensors.proximity.enabled", false);
// user_pref("dom.battery.enabled", false);
// user_pref("dom.private-attribution.submission.enabled", false);
// user_pref("dom.webaudio.enabled", false);
// user_pref("experiments.activeExperiment", false);
// user_pref("experiments.enabled", false);
// user_pref("experiments.manifest.uri", "");
// user_pref("experiments.supported", false);
// user_pref("extensions.Decentraleyes@ThomasRientjes.whiteList", "");
// user_pref("extensions.FirefoxMulti-AccountContainers@mozilla.whiteList", "");
// user_pref("extensions.autoDisableScopes", 14);
// user_pref("extensions.blocklist.enabled", false);
// user_pref("extensions.getAddons.cache.enabled", false);
// user_pref("extensions.getAddons.showPane", false);
// user_pref("extensions.greasemonkey.stats.optedin", false);
// user_pref("extensions.greasemonkey.stats.url", "");
// user_pref("extensions.pocket.enabled", false);
// user_pref("extensions.shield-recipe-client.api_url", "");
// user_pref("extensions.shield-recipe-client.enabled", false);
// user_pref("extensions.webservice.discoverURL", "");
// user_pref("media.autoplay.default", 0);
// user_pref("media.autoplay.enabled", true);
// user_pref("media.navigator.enabled", false);
// user_pref("media.peerconnection.enabled", false);
// user_pref("media.video_stats.enabled", false);
// user_pref("network.allow-experiments", false);
// user_pref("network.captive-portal-service.enabled", false);
// user_pref("network.cookie.cookieBehavior", 1);
// user_pref("network.dns.disablePrefetch", true);
// user_pref("network.dns.disablePrefetchFromHTTPS", true);
// user_pref("network.http.referer.spoofSource", true);
// user_pref("network.http.speculative-parallel-limit", 0);
// user_pref("network.predictor.enable-prefetch", false);
// user_pref("network.predictor.enabled", false);
// user_pref("network.prefetch-next", false);
// user_pref("network.trr.mode", 5);
// user_pref("privacy.donottrackheader.enabled", true);
// user_pref("privacy.donottrackheader.value", 1);
// user_pref("privacy.query_stripping", true);
// user_pref("privacy.trackingprotection.cryptomining.enabled", true);
// user_pref("privacy.trackingprotection.enabled", true);
// user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
// user_pref("privacy.trackingprotection.pbmode.enabled", true);
// user_pref("privacy.usercontext.about_newtab_segregation.enabled", true);
// user_pref("security.ssl.disable_session_identifiers", true);
// user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite", false);
// user_pref("signon.autofillForms", false);
// user_pref("toolkit.telemetry.archive.enabled", false);
// user_pref("toolkit.telemetry.bhrPing.enabled", false);
// user_pref("toolkit.telemetry.cachedClientID", "");
// user_pref("toolkit.telemetry.enabled", false);
// user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
// user_pref("toolkit.telemetry.hybridContent.enabled", false);
// user_pref("toolkit.telemetry.newProfilePing.enabled", false);
// user_pref("toolkit.telemetry.prompted", 2);
// user_pref("toolkit.telemetry.rejected", true);
// user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
// user_pref("toolkit.telemetry.server", "");
// user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
// user_pref("toolkit.telemetry.unified", false);
// user_pref("toolkit.telemetry.unifiedIsOptIn", false);
// user_pref("toolkit.telemetry.updatePing.enabled", false);
// user_pref("webgl.disabled", true);
// user_pref("webgl.renderer-string-override", " ");
// user_pref("webgl.vendor-string-override", " ");
