desktop:
  screen: "1920x1080@60"

member:
  # needed for legacy API ad there is no user management
  provider: "multiuser"
  multiuser:
   admin_password: "admin"
   user_password: "neko"

session:
  merciful_reconnect: true
  # default setting for legacy API
  implicit_hosting: false
  cookie:
    # needed for legacy API
    enabled: false
